/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ant */

#ifndef _Included_Ant
#define _Included_Ant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ant
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Ant_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
